<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="7.1.0" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.18.7" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.2.15" />
    <PackageReference Include="AWSSDK.CloudFront" Version="4.0.12.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="StackExchange.Redis" Version="2.11.8" />
    <PackageReference Include="System.Runtime.Caching" Version="10.0.3" />
    <PackageReference Include="TimePeriodLibrary.NET" Version="2.1.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevSu.Bank.Accounts.Application\DevSu.Bank.Accounts.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AggregateDataContext\Configurations\" />
    <Folder Include="AggregateRepositories\" />
    <Folder Include="Exceptions\" />
    <Folder Include="ReadOnlyDataContext\Configurations\" />
    <Folder Include="ReadOnlyRepositories\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DevSu.Bank.Accounts.Infrastructure.UnitTest" />
  </ItemGroup>

</Project>
