server {
    listen 8080;

    location /status {
        return 200 "Healthy";
        add_header Content-Type text/plain;
    }

    location /api/v1/clientes {
        proxy_pass http://customers-api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ~ ^/api/v1/(cuentas|movimientos|reportes) {
        proxy_pass http://accounts-api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
