// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DevSu.Bank.Customers.Application.ReadOnlyModels;
using DevSu.Bank.Customers.Infrastructure.ReadOnlyDataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DevSu.Bank.Customers.Infrastructure.ReadOnlyDataContext.Configurations
{
    public partial class ClientConfiguration : IEntityTypeConfiguration<Client>
    {
        public void Configure(EntityTypeBuilder<Client> entity)
        {
            entity.HasIndex(e => e.ClientId, "UQ_Clients_ClientId").IsUnique();

            entity.HasIndex(e => e.Identification, "UQ_Clients_Identification").IsUnique();

            entity.Property(e => e.Address).HasMaxLength(250);
            entity.Property(e => e.ClientId).HasMaxLength(20);
            entity.Property(e => e.Gender).HasComment("1 = Male, 2 = Female, 3 = Other");
            entity.Property(e => e.Identification).HasMaxLength(30);
            entity.Property(e => e.Name).HasMaxLength(150);
            entity.Property(e => e.PasswordHash).HasMaxLength(200);
            entity.Property(e => e.Phone).HasMaxLength(30);
            entity.Property(e => e.Status).HasDefaultValue(true, "DF_Clients_Status");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Client> entity);
    }
}
