// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DevSu.Bank.Accounts.Application.ReadOnlyModels;
using DevSu.Bank.Accounts.Infrastructure.ReadOnlyDataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DevSu.Bank.Accounts.Infrastructure.ReadOnlyDataContext.Configurations
{
    public partial class TransactionConfiguration : IEntityTypeConfiguration<Transaction>
    {
        public void Configure(EntityTypeBuilder<Transaction> entity)
        {
            entity.HasIndex(e => new { e.AccountId, e.TransactionDate }, "IX_Transactions_Account_Date");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Balance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransactionDate)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_Transactions_Date");
            entity.Property(e => e.TransactionType).HasComment("1 = Deposit, 2 = Withdrawal");

            entity.HasOne(d => d.Account).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Transactions_Accounts");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Transaction> entity);
    }
}
