//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevSu.Bank.Customers.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Generals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Generals() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevSu.Bank.Customers.Domain.Resources.Generals", typeof(Generals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter &apos;{0}&apos; must be greater than or equal to &apos;{1}&apos;.
        /// </summary>
        public static string GreaterOrEqualTo {
            get {
                return ResourceManager.GetString("GreaterOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter &apos;{0}&apos; must be less or equal than &apos;{1}&apos;.
        /// </summary>
        public static string LessThanOrEqualThanTo {
            get {
                return ResourceManager.GetString("LessThanOrEqualThanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter &apos;{0}&apos; can not be empty or null.
        /// </summary>
        public static string NotEmptyOrNullParameter {
            get {
                return ResourceManager.GetString("NotEmptyOrNullParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One or more validation errors occurred.
        /// </summary>
        public static string OneOrMoreValidationErrorsOccurred {
            get {
                return ResourceManager.GetString("OneOrMoreValidationErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown error.
        /// </summary>
        public static string UnkownError {
            get {
                return ResourceManager.GetString("UnkownError", resourceCulture);
            }
        }
    }
}
