<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <UserSecretsId>76686111-a7f6-476a-88cb-80019f2891cd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\V2\**" />
    <Content Remove="Controllers\V2\**" />
    <EmbeddedResource Remove="Controllers\V2\**" />
    <None Remove="Controllers\V2\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevSu.Bank.Customers.Infrastructure\DevSu.Bank.Customers.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\V1\" />
  </ItemGroup>

</Project>
